# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=example
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8099:8080

  web:
    build:
      context: inventoryui
    volumes:
      - './inventoryui:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '80:4200'
    command: ng serve --host 0.0.0.0 --disable-host-check

  api:
    build:
      context: inventoryapi
    links:
      - db
    ports:
      - '8080:8080'
