package com.horosin.dawn.controllers;

import com.horosin.dawn.model.Sample;
import com.horosin.dawn.repository.SampleRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.*;

import java.util.Optional;

@RestController
public class SampleController {

    // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    @Autowired
    private SampleRepository sampleRepository;

    @GetMapping("/hello")
    public String getHelloMessage(){
        return "Welcome to Lab API";
    }

    @PostMapping("/samples")
    @ResponseStatus(HttpStatus.CREATED)
    public Sample createNewSample(@RequestBody Sample sample) {

        sampleRepository.save(sample);

        return sample;
    }

    @GetMapping("/samples")
    public Iterable<Sample> getAllSamples() {
        return sampleRepository.findAll();

    }

    @GetMapping("/samples/{id}")
    public Sample getSample(@PathVariable("id") Integer sampleId) {

        Optional<Sample> sample = sampleRepository.findById(sampleId);

        if(sample.isPresent()) {
            return sample.get();
        }

        throw new IllegalArgumentException();

    }

    @PostMapping("/samples/{id}")
    public Sample updateSample(
            @PathVariable("id") Integer sampleId,
            @RequestBody Sample newSample
    ) {

        if(!sampleRepository.existsById(sampleId)) {
            throw new IllegalArgumentException();
        }

        newSample.setId(sampleId);
        sampleRepository.save(newSample);

        return newSample;
    }

    // Exception handler for wrong requests
    @ResponseStatus(value = HttpStatus.BAD_REQUEST,
            reason = "Requested id not found")
    @ExceptionHandler(IllegalArgumentException.class)
    public void wrongIdHandler() {

    }
}
